apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: postgres
type: Opaque
stringData:
  postgres-password: "<POSTGRES_PASSWORD>"
  postgres-replication-password: "<POSTGRES_REPLICATION_PASSWORD>"
