# postgres-values.yaml
global:
  postgresql:
    auth:
      database: "laravel"
      existingSecret: "postgres-credentials"
      secretKeys:
        adminPasswordKey: postgres-password
        replicationPasswordKey: postgres-replication-password

architecture: replication

primary:
  nodeSelector:
    kubernetes.io/hostname: tauntoncross
  networkPolicy:
    enabled: false

  persistence:
    size: 8Gi

  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 2Gi
      cpu: 2

  extendedConfiguration: |
    listen_addresses = '*'
    synchronous_commit = off
    synchronous_standby_names = ''
    max_wal_senders = 10
    max_replication_slots = 10

readReplicas:
  extendedConfiguration: |
    hot_standby = on
    hot_standby_feedback = on
    max_standby_streaming_delay = -1
    max_standby_archive_delay = -1
    max_wal_senders = 10
    max_replication_slots = 10
  ## Startup probe: Disables other probes until this one passes
  ## This is ideal for long initial replications.
  startupProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 60 # 60 * 10s = 10 minutes to finish cloning
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  replicaCount: 2
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
              app.kubernetes.io/component: read
          topologyKey: "kubernetes.io/hostname"
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 1

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus

  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 300m

backup:
  enabled: false
  cronjob:
    schedule: "0 2 * * *"
    storage:
      persistentVolumeClaim:
        size: 8Gi

extraDeploy:
  - |
    apiVersion: v1
    kind: Service
    metadata:
      name: postgres-postgresql-read-local
      labels:
        app.kubernetes.io/component: read
        app.kubernetes.io/instance: postgres
        app.kubernetes.io/name: postgresql
    spec:
      type: ClusterIP
      internalTrafficPolicy: Local
      ports:
        - name: postgresql
          port: 5432
          targetPort: 5432
      selector:
        app.kubernetes.io/component: read
        app.kubernetes.io/instance: postgres
        app.kubernetes.io/name: postgresql
