apiVersion: v1
kind: Secret
metadata:
  name: github-app-secret
  namespace: arc-systems
type: Opaque
stringData:
  github_app_id: "<GITHUB_APP_ID>"
  github_app_installation_id: "<GITHUB_APP_INSTALLATION_ID>"
  github_app_private_key: |
    <GITHUB_APP_PRIVATE_KEY>
